### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by cohoe** [cohoe/starrs-web#50]
"Addresses in range are inuse" does not catch DBException and print a nice error message.

**Comment by cohoe** [comment]
Fatal error: Uncaught exception 'DBException' with message 'ERROR: All addresses in range User Machines are in use' in /var/www/priv/impulse/application/libraries/core/ImpulseModel.php:25 Stack trace: #0 /var/www/priv/impulse/application/models/API/IP/api_ip_get.php(15): ImpulseModel->_check_error(false) #1 /var/www/priv/impulse/application/controllers/computer_system.php(240): Api_ip_get->address_from_range('User Machines') #2 [internal function]: Computer_system->quickcreate() #3 /var/www/priv/impulse/ci_system/core/CodeIgniter.php(339): call_user_func_array(Array, Array) #4 /var/www/priv/impulse/index.php(201): require_once('/var/www/priv/i...') #5 {main} thrown in /var/www/priv/impulse/application/libraries/core/ImpulseModel.php on line 25

**Comment by cohoe** [comment]
Not-an-issue as of 3d1856c7e4bc0306d5086e009e7205a1c79739e0
